---

# Thruster 1 - Surge thruster left side
- ros_topic_name: "/model/blueye/joint/blueye_thruster_1_joint/cmd_thrust"
  gz_topic_name: "/model/blueye/joint/blueye_thruster_1_joint/cmd_thrust"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ

# Thruster 2 - Surge thruster right side
- ros_topic_name: "/model/blueye/joint/blueye_thruster_2_joint/cmd_thrust"
  gz_topic_name: "/model/blueye/joint/blueye_thruster_2_joint/cmd_thrust"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ

# Thruster 3 - Sway thruster
- ros_topic_name: "/model/blueye/joint/blueye_thruster_3_joint/cmd_thrust"
  gz_topic_name: "/model/blueye/joint/blueye_thruster_3_joint/cmd_thrust"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ

# Thruster 4 - Heave thruster
- ros_topic_name: "/model/blueye/joint/blueye_thruster_4_joint/cmd_thrust"
  gz_topic_name: "/model/blueye/joint/blueye_thruster_4_joint/cmd_thrust"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ

# Odometry
- ros_topic_name: "/blueye/odometry_flu/gt"
  gz_topic_name: "/blueye/odometry_flu/gt"
  ros_type_name: "nav_msgs/msg/Odometry"
  gz_type_name: "gz.msgs.Odometry"
  direction: GZ_TO_ROS

# IMU
- ros_topic_name: "/blueye/imu"
  gz_topic_name: "/blueye/imu"
  ros_type_name: "sensor_msgs/msg/Imu"
  gz_type_name: "gz.msgs.IMU"
  direction: GZ_TO_ROS

# Front camera  - RGB
- ros_topic_name: "/blueye/camera/front_camera/image_raw"
  gz_topic_name: "/blueye/camera/front_camera/image_raw"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "sensor_msgs/Image"
  direction: GZ_TO_ROS

# DVL RAY - RAY sensor used to find altitude for DVL
- ros_topic_name: "/blueye/dvl_ray"
  gz_topic_name: "/blueye/dvl_ray"
  ros_type_name: "sensor_msgs/msg/LaserScan"
  gz_type_name: "gz.msgs.Range"
  direction: GZ_TO_ROS